
NANOJIT_CXXFLAGS=-DFEATURE_NANOJIT -DAVMPLUS_IA32 -D_DEBUG -DNJ_VERBOSE -DNJ_PROFILE \
                 -DDEBUGGER -DMGC_INTERIOR_PTRS -DLINUX -DSOFT_ASSERTS -DAVMPLUS_LINUX -DAVMPLUS_UNIX\
                 -msse2  -g -fPIC -Wall
